namespace MiddlewareExample.CustomMiddleware // This is necessary when the middleware is inside of a folder
{
    public class MyCustomMiddleware : IMiddleware // This is to bring the methods of the interface
    { //This is generated by right click and quick action and implement interface
        public async Task InvokeAsync(HttpContext context, RequestDelegate next) 
        {
            await context.Response.WriteAsync("My Custom Middleware - Starts");
            await next(context);
            await context.Response.WriteAsync("My Custom Middleware - Ends");
        }
    }
}
